version: '2'
services:
  musicplaylistmicroservice:
    image: chest/music-playlist-microservice
    ports:
      - "5050:5050"
  elasticsearch:
    image: elasticsearch:5.5.2
    ports:
      - "9200:9200"
  kibana:
    image: kibana:5.5.2
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
  logstash:
    image: logstash:5.5.2
    command: -e 'input { tcp { port => 5555 } } output { elasticsearch { hosts => ["elasticsearch:9200"] } }'
    ports:
      - "5555:5555"
    depends_on:
      - elasticsearch
  grafana:
    image: "grafana/grafana:4.3.1"
    ports:
      - "3000:3000"